<?php

namespace MediaWiki\Extension\StructureSync\Generator;

use MediaWiki\Extension\StructureSync\Schema\CategoryModel;
use MediaWiki\Extension\StructureSync\Schema\FormatSchemaReader;
use MediaWiki\Extension\StructureSync\Store\PageCreator;
use MediaWiki\Extension\StructureSync\Store\WikiPropertyStore;
use MediaWiki\Extension\StructureSync\Util\NamingHelper;

/**
 * DisplayStubGenerator (Redesigned 2025)
 * ---------------------------------------
 * Creates Template:<Category>/display with static property template calls.
 *
 * Design rules:
 *   - Generates static wikitext with explicit property template calls
 *   - Uses format schemas (TemplateFormat categories) to determine layout
 *   - Example: {{ Property/Has email | {{{email|}}} }}
 *   - Falls back to Template:Property/Default for properties without custom templates
 *   - User-editable after generation
 *
 * The generated template is static and inspectable, making it easy to customize
 * while still being regeneratable when needed.
 */
class DisplayStubGenerator {

    private PageCreator $pageCreator;
    private WikiPropertyStore $propertyStore;
    private FormatSchemaReader $formatReader;

    public function __construct(
        ?PageCreator $pageCreator = null,
        ?WikiPropertyStore $propertyStore = null,
        ?FormatSchemaReader $formatReader = null
    ) {
        $this->pageCreator   = $pageCreator   ?? new PageCreator();
        $this->propertyStore = $propertyStore ?? new WikiPropertyStore();
        $this->formatReader  = $formatReader  ?? new FormatSchemaReader();
    }

    /* =====================================================================
     * INTERNAL UTILS
     * ===================================================================== */

    private function sanitize(?string $value): string {
        return $value ?? '';
    }

    private function makeDisplayTitle(string $categoryName) {
        return $this->pageCreator->makeTitle(
            $categoryName . '/display',
            NS_TEMPLATE
        );
    }

    /* =====================================================================
     * MAIN GENERATION
     * ===================================================================== */

    /**
     * Generates the *content* of the display template.
     *
     * Creates static wikitext with explicit property template calls,
     * using the category's renderAs format or defaulting to sections layout.
     */
    public function generateDisplayStub(CategoryModel $category): string {

        $cat = $this->sanitize($category->getName());
        $lines = [];

        /* ------------------------------------------------------------------
         * NOINCLUDE header
         * ------------------------------------------------------------------ */
        $lines[] = '<noinclude>';
        $lines[] = '<!-- DISPLAY TEMPLATE (AUTO-GENERATED by StructureSync) -->';
        $lines[] = '<!-- SAFE TO EDIT. Regenerate to update with schema changes. -->';
        $lines[] = '<!-- Template calls:  {{ Property/PropertyName | {{{param|}}} }} -->';
        $lines[] = '<!-- Default fallback: {{ Property/Default | label=Name | {{{param|}}} }} -->';
        $lines[] = '</noinclude>';

        /* ------------------------------------------------------------------
         * GENERATED PROPERTY TEMPLATE CALLS
         * ------------------------------------------------------------------ */
        $lines[] = '<includeonly>';
        
        // Get format schema and compose property calls
        $formatName = $category->getRenderAs();
        $format = $this->formatReader->readFormatOrDefault($formatName);
        
        $propertyContent = $this->formatReader->composePropertyCalls($format, $category);
        $lines[] = $propertyContent;
        
        // Include hierarchy widget
        $lines[] = '';
        $lines[] = '{{#structuresync_hierarchy:}}';
        $lines[] = '</includeonly>';

        return implode("\n", $lines);
    }

    /* =====================================================================
     * STUB CREATION LOGIC
     * ===================================================================== */

    /**
     * True if Template:<Category>/display exists.
     */
    public function displayStubExists(string $categoryName): bool {
        $title = $this->makeDisplayTitle($categoryName);
        return $title && $this->pageCreator->pageExists($title);
    }

    /**
     * Creates the stub ONLY if missing.
     *
     * Returns:
     *   [
     *     'created' => bool,
     *     'message' => string,
     *     'error'   => string (optional)
     *   ]
     */
    public function generateDisplayStubIfMissing(CategoryModel $category): array {

        $name = $category->getName();

        if ($this->displayStubExists($name)) {
            return [
                'created' => false,
                'message' => 'Display template already exists; not overwritten.'
            ];
        }

        $content = $this->generateDisplayStub($category);
        $title   = $this->makeDisplayTitle($name);

        if (!$title) {
            return [
                'created' => false,
                'error'   => 'Failed to create Title object for display template.'
            ];
        }

        $ok = $this->pageCreator->createOrUpdatePage(
            $title,
            $content,
            'StructureSync: Initial display stub (safe to edit)'
        );

        if (!$ok) {
            return [
                'created' => false,
                'error'   => 'Failed to write display template.'
            ];
        }

        return [
            'created' => true,
            'message' => 'Display template stub created.'
        ];
    }

    /**
     * FORCED update — overwrites user customizations.
     * Use ONLY manually.
     *
     * Returns:
     *   [
     *     'created' => bool,
     *     'updated' => bool,
     *     'message' => string,
     *     'error'   => string (optional)
     *   ]
     */
    public function generateOrUpdateDisplayStub(CategoryModel $category): array {

        $name    = $category->getName();
        $existed = $this->displayStubExists($name);

        $content = $this->generateDisplayStub($category);
        $title   = $this->makeDisplayTitle($name);

        if (!$title) {
            return [
                'created' => false,
                'updated' => false,
                'error'   => 'Failed to create Title object for display template.'
            ];
        }

        $summary = $existed
            ? 'StructureSync: Updated display template'
            : 'StructureSync: Initial display stub (safe to edit)';

        $ok = $this->pageCreator->createOrUpdatePage($title, $content, $summary);

        if (!$ok) {
            return [
                'created' => false,
                'updated' => false,
                'error'   => 'Failed to write display template.'
            ];
        }

        return [
            'created' => !$existed,
            'updated' => $existed,
            'message' => $existed ? 'Display template updated.' : 'Display template stub created.'
        ];
    }

    /* =====================================================================
     * LABEL / PARAM NAME HELPERS (unused by stub but preserved)
     * ===================================================================== */

    private function propertyToParameter(string $propertyName): string {
        return NamingHelper::propertyToParameter($propertyName);
    }

    private function propertyToLabel(string $propertyName): string {
        $propertyName = $this->sanitize($propertyName);

        $model = $this->propertyStore->readProperty($propertyName);
        if ($model) {
            return $model->getLabel();
        }

        return NamingHelper::generatePropertyLabel($propertyName);
    }
}
