<?php

namespace MediaWiki\Extension\StructureSync\Generator;

use MediaWiki\Extension\StructureSync\Schema\CategoryModel;
use MediaWiki\Extension\StructureSync\Store\PageCreator;

/**
 * Generates initial display template stubs for categories
 * Never overwrites existing display templates
 */
class DisplayStubGenerator {

	/** @var PageCreator */
	private $pageCreator;

	/**
	 * @param PageCreator|null $pageCreator
	 */
	public function __construct( PageCreator $pageCreator = null ) {
		$this->pageCreator = $pageCreator ?? new PageCreator();
	}

	/**
	 * Generate display template stub for a category
	 *
	 * @param CategoryModel $category
	 * @return string Template wikitext
	 */
	public function generateDisplayStub( CategoryModel $category ): string {
		$lines = [];

		$lines[] = '<noinclude>';
		$lines[] = '<!-- DISPLAY TEMPLATE STUB generated by StructureSync -->';
		$lines[] = '<!-- This template is SAFE TO EDIT and will NOT be overwritten -->';
		$lines[] = '<!-- Customize the display layout for [[Category:' . $category->getName() . ']] pages here -->';
		$lines[] = '</noinclude><includeonly>';

		// Generate header section
		$headerProperties = $category->getDisplayHeaderProperties();
		if ( !empty( $headerProperties ) ) {
			$lines[] = '<div class="category-header">';
			foreach ( $headerProperties as $property ) {
				$paramName = $this->propertyToParameter( $property );
				$lines[] = "  <h1>{{{" . $paramName . "}}}</h1>";
			}
			$lines[] = '</div>';
			$lines[] = '';
		}

		// Generate sections based on display config
		$sections = $category->getDisplaySections();
		if ( !empty( $sections ) ) {
			foreach ( $sections as $section ) {
				$lines = array_merge( $lines, $this->generateDisplaySection( $section ) );
			}
		} else {
			// Fallback: generate basic sections for all properties
			$lines = array_merge( $lines, $this->generateDefaultDisplaySection( $category ) );
		}

		$lines[] = '</includeonly>';

		return implode( "\n", $lines );
	}

	/**
	 * Generate a display section
	 *
	 * @param array $section Section config with 'name' and 'properties'
	 * @return array Lines of wikitext
	 */
	private function generateDisplaySection( array $section ): array {
		$lines = [];

		$sectionName = $section['name'] ?? 'Untitled';
		$lines[] = "== $sectionName ==";
		$lines[] = '<div class="display-section">';

		$properties = $section['properties'] ?? [];
		foreach ( $properties as $propertyName ) {
			$paramName = $this->propertyToParameter( $propertyName );
			$label = $this->propertyToLabel( $propertyName );

			$lines[] = "  {{#if:{{{" . $paramName . "|}}}|";
			$lines[] = "    <div class=\"property-row\">";
			$lines[] = "      <span class=\"property-label\">'''" . $label . ":'''</span>";
			$lines[] = "      <span class=\"property-value\">{{{" . $paramName . "}}}</span>";
			$lines[] = "    </div>";
			$lines[] = "  }}";
		}

		$lines[] = '</div>';
		$lines[] = '';

		return $lines;
	}

	/**
	 * Generate default display section with all properties
	 *
	 * @param CategoryModel $category
	 * @return array Lines of wikitext
	 */
	private function generateDefaultDisplaySection( CategoryModel $category ): array {
		$lines = [];

		$allProperties = $category->getAllProperties();
		if ( !empty( $allProperties ) ) {
			$lines[] = '== Details ==';
			$lines[] = '<div class="display-section">';

			foreach ( $allProperties as $propertyName ) {
				$paramName = $this->propertyToParameter( $propertyName );
				$label = $this->propertyToLabel( $propertyName );

				$lines[] = "  {{#if:{{{" . $paramName . "|}}}|";
				$lines[] = "    <div class=\"property-row\">";
				$lines[] = "      <span class=\"property-label\">'''" . $label . ":'''</span>";
				$lines[] = "      <span class=\"property-value\">{{{" . $paramName . "}}}</span>";
				$lines[] = "    </div>";
				$lines[] = "  }}";
			}

			$lines[] = '</div>';
			$lines[] = '';
		}

		return $lines;
	}

	/**
	 * Check if display stub exists
	 *
	 * @param string $categoryName
	 * @return bool
	 */
	public function displayStubExists( string $categoryName ): bool {
		$title = $this->pageCreator->makeTitle( $categoryName . '/display', NS_TEMPLATE );
		return $title !== null && $this->pageCreator->pageExists( $title );
	}

	/**
	 * Generate and save display stub if it doesn't exist
	 *
	 * @param CategoryModel $category
	 * @return array Result with 'created' bool and optional 'error' message
	 */
	public function generateDisplayStubIfMissing( CategoryModel $category ): array {
		$categoryName = $category->getName();

		// Check if display template already exists
		if ( $this->displayStubExists( $categoryName ) ) {
			return [
				'created' => false,
				'message' => 'Display template already exists, not overwriting',
			];
		}

		// Generate stub content
		$content = $this->generateDisplayStub( $category );

		// Create the page
		$title = $this->pageCreator->makeTitle( $categoryName . '/display', NS_TEMPLATE );
		if ( $title === null ) {
			return [
				'created' => false,
				'error' => 'Failed to create title',
			];
		}

		$summary = 'StructureSync: Generated display template stub (safe to edit)';
		$success = $this->pageCreator->createOrUpdatePage( $title, $content, $summary );

		if ( $success ) {
			return [
				'created' => true,
				'message' => 'Display template stub created',
			];
		} else {
			return [
				'created' => false,
				'error' => 'Failed to create page',
			];
		}
	}

	/**
	 * Convert property name to template parameter name
	 *
	 * @param string $propertyName
	 * @return string
	 */
	private function propertyToParameter( string $propertyName ): string {
		// Remove "Has " prefix if present
		$param = $propertyName;
		if ( str_starts_with( $param, 'Has ' ) ) {
			$param = substr( $param, 4 );
		}

		// Convert to lowercase with underscores
		$param = strtolower( $param );
		$param = str_replace( ' ', '_', $param );

		return $param;
	}

	/**
	 * Convert property name to human-readable label
	 *
	 * @param string $propertyName
	 * @return string
	 */
	private function propertyToLabel( string $propertyName ): string {
		// Remove "Has " prefix if present
		$label = $propertyName;
		if ( str_starts_with( $label, 'Has ' ) ) {
			$label = substr( $label, 4 );
		}

		return $label;
	}
}

