<?php

namespace MediaWiki\Extension\StructureSync\Generator;

use MediaWiki\Extension\StructureSync\Schema\CategoryModel;
use MediaWiki\Extension\StructureSync\Schema\PropertyModel;
use MediaWiki\Extension\StructureSync\Store\PageCreator;
use MediaWiki\Extension\StructureSync\Store\WikiPropertyStore;

/**
 * Generates PageForms forms for categories
 */
class FormGenerator {

	/** @var PageCreator */
	private $pageCreator;

	/** @var WikiPropertyStore */
	private $propertyStore;

	/** @var PropertyInputMapper */
	private $inputMapper;

	/**
	 * @param PageCreator|null $pageCreator
	 * @param WikiPropertyStore|null $propertyStore
	 * @param PropertyInputMapper|null $inputMapper
	 */
	public function __construct(
		PageCreator $pageCreator = null,
		WikiPropertyStore $propertyStore = null,
		PropertyInputMapper $inputMapper = null
	) {
		$this->pageCreator = $pageCreator ?? new PageCreator();
		$this->propertyStore = $propertyStore ?? new WikiPropertyStore();
		$this->inputMapper = $inputMapper ?? new PropertyInputMapper();
	}

	/**
	 * Generate a PageForms form for a category
	 *
	 * @param CategoryModel $category
	 * @return string Form wikitext
	 */
	public function generateForm( CategoryModel $category ): string {
		$lines = [];

		$lines[] = '<noinclude>';
		$lines[] = '<!-- AUTO-GENERATED by StructureSync - DO NOT EDIT MANUALLY -->';
		$lines[] = '<!-- This form is automatically regenerated -->';
		$lines[] = 'This is the form for editing [[Category:' . $category->getName() . ']] pages.';
		$lines[] = '</noinclude><includeonly>';

		// Form header
		$lines[] = '{{{info';
		$lines[] = '|page name=<' . $category->getLabel() . '>';
		$lines[] = '|create title=Create new ' . $category->getLabel();
		$lines[] = '|edit title=Edit ' . $category->getLabel();
		$lines[] = '}}}';
		$lines[] = '';

		// Form body
		$lines[] = '{{{for template|' . $category->getName() . '}}}';
		$lines[] = '';

		// Generate sections based on form config or fallback to properties
		$formSections = $category->getFormSections();
		if ( !empty( $formSections ) ) {
			foreach ( $formSections as $section ) {
				$lines = array_merge( $lines, $this->generateFormSection( $section, $category ) );
			}
		} else {
			// Fallback: generate a single section with all properties
			$lines = array_merge( $lines, $this->generateDefaultFormSection( $category ) );
		}

		$lines[] = '{{{end template}}}';
		$lines[] = '';

		// Summary and buttons
		$lines[] = '{{{standard input|summary}}}';
		$lines[] = '';
		$lines[] = '{{{standard input|save}}} {{{standard input|preview}}} {{{standard input|changes}}} {{{standard input|cancel}}}';

		$lines[] = '</includeonly>';

		return implode( "\n", $lines );
	}

	/**
	 * Generate a form section
	 *
	 * @param array $section Section config with 'name' and 'properties'
	 * @param CategoryModel $category
	 * @return array Lines of wikitext
	 */
	private function generateFormSection( array $section, CategoryModel $category ): array {
		$lines = [];

		$sectionName = $section['name'] ?? 'Untitled';
		$lines[] = "=== $sectionName ===";
		$lines[] = '';

		$properties = $section['properties'] ?? [];
		foreach ( $properties as $propertyName ) {
			$lines = array_merge( $lines, $this->generateFieldDefinition( $propertyName, $category ) );
		}

		$lines[] = '';

		return $lines;
	}

	/**
	 * Generate default form section with all properties
	 *
	 * @param CategoryModel $category
	 * @return array Lines of wikitext
	 */
	private function generateDefaultFormSection( CategoryModel $category ): array {
		$lines = [];

		// Required properties first
		if ( !empty( $category->getRequiredProperties() ) ) {
			$lines[] = '=== Required Information ===';
			$lines[] = '';
			foreach ( $category->getRequiredProperties() as $propertyName ) {
				$lines = array_merge( $lines, $this->generateFieldDefinition( $propertyName, $category ) );
			}
			$lines[] = '';
		}

		// Optional properties
		if ( !empty( $category->getOptionalProperties() ) ) {
			$lines[] = '=== Additional Information ===';
			$lines[] = '';
			foreach ( $category->getOptionalProperties() as $propertyName ) {
				$lines = array_merge( $lines, $this->generateFieldDefinition( $propertyName, $category ) );
			}
			$lines[] = '';
		}

		return $lines;
	}

	/**
	 * Generate field definition for a property
	 *
	 * @param string $propertyName
	 * @param CategoryModel $category
	 * @return array Lines of wikitext
	 */
	private function generateFieldDefinition( string $propertyName, CategoryModel $category ): array {
		$lines = [];

		// Get property model
		$property = $this->propertyStore->readProperty( $propertyName );
		if ( $property === null ) {
			// Property doesn't exist, create a basic text field
			$property = new PropertyModel( $propertyName, [ 'datatype' => 'Text' ] );
		}

		// Check if required
		$isMandatory = $category->isPropertyRequired( $propertyName );

		// Generate field label
		$label = $property->getLabel();
		$lines[] = "'''" . $label . ":'''";

		// Generate input definition
		$inputDef = $this->inputMapper->generateInputDefinition( $property, $isMandatory );
		$paramName = $this->propertyToParameter( $propertyName );
		$lines[] = '{{{field|' . $paramName . '|' . $inputDef . '}}}';
		$lines[] = '';

		return $lines;
	}

	/**
	 * Update or create a form
	 *
	 * @param string $formName Form name (without "Form:" prefix)
	 * @param string $content Form wikitext
	 * @return bool True on success
	 */
	public function updateForm( string $formName, string $content ): bool {
		$title = $this->pageCreator->makeTitle( $formName, PF_NS_FORM );
		if ( $title === null ) {
			return false;
		}

		$summary = 'StructureSync: Auto-generated form';
		return $this->pageCreator->createOrUpdatePage( $title, $content, $summary );
	}

	/**
	 * Generate and save form for a category
	 *
	 * @param CategoryModel $category
	 * @return bool True on success
	 */
	public function generateAndSaveForm( CategoryModel $category ): bool {
		$formContent = $this->generateForm( $category );
		return $this->updateForm( $category->getName(), $formContent );
	}

	/**
	 * Convert property name to template parameter name
	 *
	 * @param string $propertyName
	 * @return string
	 */
	private function propertyToParameter( string $propertyName ): string {
		// Remove "Has " prefix if present
		$param = $propertyName;
		if ( str_starts_with( $param, 'Has ' ) ) {
			$param = substr( $param, 4 );
		}

		// Convert to lowercase with underscores
		$param = strtolower( $param );
		$param = str_replace( ' ', '_', $param );

		return $param;
	}

	/**
	 * Check if form exists for a category
	 *
	 * @param string $categoryName
	 * @return bool
	 */
	public function formExists( string $categoryName ): bool {
		$title = $this->pageCreator->makeTitle( $categoryName, PF_NS_FORM );
		return $title !== null && $this->pageCreator->pageExists( $title );
	}
}

